### PR TITLE
Changed gitfetch to fetchquest, I changed all the code unless it was …

### PR DESCRIPTION
**Pull request by peskaypea**
I changed all the code unless it was a link to this repo or linked to .gif.

## Status

**READY**

## Description

As you requested I change the gitfetch to a new name which is fetchquest. 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [x ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by infm5** [comment]
@peskaypea is the name `gitfetch` that bad?😅

**Comment by peskaypea** [comment]
@deepraj02 Not at all, though finding a unique catchy name that doesn't relate to other commands is important 😊

**Comment by ArshErgon** [comment]
@deepraj02 its an issue #45, he forget to mention the issue in his PR
Hey @peskaypea thanks for your PR! I have seen you have change every occurrence of `gitfetch` to `fetchquest`
but I was thinking a name similar to `gitgrab` or `onefetch` what you think?
Overall the PR is good, I really appreciate your time and effort on this.

**Comment by peskaypea** [comment]
Sure thing I will update with gitgrab @ArshErgon

**Comment by peskaypea** [comment]
updated in my latest commit @ArshErgon

**Comment by ArshErgon** [comment]
LGTM! @peskaypea thanks for your wonderful PR

**Pull request merged**
